apiVersion: apps/v1
kind: Deployment
metadata:
  name: direct-messaging
  labels:
    app: direct-messaging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: direct-messaging
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: direct-messaging
        app: direct-messaging
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "travelblogacr.azurecr.io/direct-messaging:{{ .Values.buildTag }}"
          resources:
            requests:
              cpu: '50m'
              memory: '100Mi'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 2
          volumeMounts:
            - name: service-secrets
              mountPath: /config/kubernetes-secrets
              readOnly: true
      volumes:
        - name: service-secrets
          secret:
            secretName: direct-messaging-secrets

