apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: direct-messaging-hpa
  labels:
    app: direct-messaging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: direct-messaging
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50