apiVersion: v1
kind: Service
metadata:
  name: direct-messaging-service
  labels:
    app: direct-messaging
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: dotnet
  selector:
    app.kubernetes.io/name: direct-messaging
    app: direct-messaging
